<?php

namespace App\Traits\Scraps;

use Illuminate\Http\Request;

trait YellDotCom
{
    // https://www.yellowpages.com/

	public function get_all_from_yell_dot_com()
    {
        $baseUrl = "https://www.yell.com/ucs/UcsSearchAction.do?keywords={{cat}}&location={{p}}&pageNum={{pn}}";

        $pc = ['B1','B31','BB1','BL1','BN1','BR1','BS1','BS16','BT1','BT36','CF10','CF24','CH5','CR0','CV37','DH1','E10','E11','E14','E15','E16','E17','E2','E3','E4','E6','G1','G12','G2','GU14','KT6','L1','LE1','LE2','LE3','LE4','LS1','M1','M20','M33','ML3','N1','N16','N17','N22','N4','N7','N8','NE1','NE3','NG1','NG16','NG17','NG5','NG7','NN1','NW1','NW10','NW2','NW3','NW6','NW9','PE1','PR1','RG1','RH10','S9','SE1','SE10','SE13','SE15','SE16','SE18','SE3','SE6','SE9','SL1','SL6','SS9','ST1','ST4','ST5','ST6','SW11','SW15','SW16','SW17','SW18','SW19','SW3','SW4','SW6','SW8','UB3','W12','W2','W3','W4','W5','W6'];

        $cats = $this->getCategories();

        $pc = ['B1'];
        // $cats =["Packaging Production"];
        $table = $this->gtc('yell_dot_com', 12);
        $data = [];
        foreach ($cats as $cat) {
            foreach ($pc as $p) {
                $pn=1;
                do {
                    \Log::Info($pn);
                    $url = str_replace(["{{cat}}","{{p}}","{{pn}}"," "], [$cat, $p, $pn, "+"], $baseUrl);
                    $resp = $this->curl_get_contents($url);
                    $page = $resp;
                    while (strpos($page, "<article")){
                        $t = $this->getScrapeValue($page, "<article", "</article>", 0);
                        $bPage = $t['v'];
                        $page = $t['nPage'];

                        $data["cat"] = $cat;
                        $data["p"] = $p;

                        $t = $this->getScrapeValue($bPage, 'data-href="', '"', 0);
                        $data["review_url"] = $t['v'];
                        $bPage = $t['nPage'];

                        $t = explode("-", $data["review_url"]);
                        $data["yell_id"] = str_replace("/","",end($t));

                        $t = $this->getScrapeValue($bPage, 'data-original="', '"', 0);
                        $data["image_url"] = $t['v'];
                        $bPage = $t['nPage'];
                        
                        $t = $this->getScrapeValue($bPage, "businessCapsule--name", "</span>", 2);
                        $data["name"] = $t['v'];
                        $bPage = $t['nPage'];

                        $t = $this->getScrapeValue($bPage, "CLASSIFICATION", "</a>", 2);
                        $data["classification"] = $t['v'];
                        $bPage = $t['nPage'];

                        $tp = $this->getPageByBounds($bPage, " Website", "<a ", "</a>");
                        $t = $this->getScrapeValue($tp, "//", '"', 0);
                        $data["website"] = $t['v'];

                        $t = $this->getScrapeValue($bPage, 'business--telephoneNumber', "<", 24);
                        $data["phone1"] = $t['v'];
                        $bPage = $t['nPage'];

                        $t = $this->getScrapeValue($bPage, 'business--telephoneNumber', "<", 24);
                        $data["phone2"] = $t['v'];
                        $bPage = $t['nPage'];

                        $t = $this->getScrapeValue($bPage, "streetAddress", "</span>", 2);
                        $data["streetAddress"] = $t['v'];
                        $bPage = $t['nPage'];

                        $t = $this->getScrapeValue($bPage, "addressLocality", "</span>", 2);
                        $data["addressLocality"] = $t['v'];
                        $bPage = $t['nPage'];

                        $t = $this->getScrapeValue($bPage, "postalCode", "</span>", 2);
                        $data["postalCode"] = $t['v'];
                        $bPage = $t['nPage'];

                        $table::create($data);

                        $data = [];
                    }
                    $pn++;
                } while ($pn <=  substr_count($resp, "pageNum"));
                break 2;
            }
        }
    }

    public function get_reviews_from_yell_dot_com()
    {
        $baseUrl = "https://www.yell.com";
        $table = $this->gtc('yell_dot_com', 12);
        $table2 = $this->gtc('yell_dot_com_reviews', 12);
        $data = [];
        foreach ($table::all() as $record) {
            $url = $baseUrl.$record->review_url;
            $resp = $this->curl_get_contents($url);
            $page = $resp;

            $t1 = $this->getScrapeValue($page, '<strong >', "<", 0);
            $t2 = $this->getScrapeValue($page, 'business--openHours"', "<", 1);
            $page = $t2['nPage'];
            $t3 = $this->getScrapeValue($page, 'business--openHours"', "<", 2);
            $data["opens_at"] = $t1['v']." / ".$t2['v']." / ".$t3['v'];
            $page = $t3['nPage'];

            $t = explode("-", $record->review_url);
            $data["yell_id"] = str_replace("/","",end($t));

            $record->update($data);

            while (strpos($page, "REVIEW:USERNAME")){

                $t = explode("-", $record->review_url);
                $data["yell_id"] = str_replace("/","",end($t));

                $t = $this->getScrapeValue($page, 'REVIEW:USERNAME', "<", 3);
                $data["user_name"] = $t['v'];
                $page = $t['nPage'];

                $t = $this->getScrapeValue($page, 'datetime="', '"', 0);
                $data["date"] = $t['v'];
                $page = $t['nPage'];

                $t = $this->getScrapeValue($page, "headline", "</div>", 3);
                $data["headline"] = $t['v'];
                $page = $t['nPage'];

                $t = $this->getScrapeValue($page, "ratingValue", "</span>", 3);
                $data["ratingValue"] = $t['v'];
                $page = $t['nPage'];

                $t = $this->getScrapeValue($page, "reviewBody", "</div>", 3);
                $data["reviewBody"] = $t['v'];
                $page = $t['nPage'];

                $table2::create($data);

                $data = [];
            }
        }
    }

    public function google_maps()
    {
        $url = "https://www.google.com/maps/search/plumbing+bengaluru";
        $resp = $this->curl_get_contents($url);
        \Log::Info($resp);
    }

    private function getCategories()
    {
        return [
            "Packaging Production",
"Packaging Design",
"Prototype Design",
"Point of Sale Design",
"Product Design",
"Logo Design",
"Email Template Design",
"Flyer & Leaflet Design",
"Business Stationery Design",
"Graphic Design",
"UX & UI Design",
"Web Design",
"Infographics",
"Video Design & Production",
"Explainer Video Services",
"Promotional Video Production",
"Training Video Production",
"Security Guard Services",
"Commercial Catering",
"Commercial Event Planning",
"Corporate Event Photography",
"Corporate Event Entertainment",
"Corporate Coach and Minibus Hire",
"Corporate Event Venue Hire",
"Venture Capital",
"Budgeting and Forecasting Services",
"Business Modelling Services",
"Business Financial Planning",
"Valuations",
"Recovery and Repossession Services",
"Statistical Analysis",
"Tax Preparation",
"Debt Recovery & Collection",
"Auditing Services",
"Payroll Services",
"Accounting",
"Business Accounting Services",
"Bookkeeping Services",
"Invoice Factoring",
"Card Processing",
"HR and Payroll Services",
"Recruiters & Head Hunters",
"Background Screening",
"HR Consulting",
"Insurers",
"Public Liability Insurance",
"Health Insurance",
"Key Man Insurance",
"Property Insurance",
"Stock Insurance",
"Directors Liability Insurance",
"Business Interruption Insurance",
"Car and Fleet Insurance",
"Employment Law Specialists",
"Arbitration Services",
"Franchising",
"Commercial Legal Services",
"Intellectual Property & Patent Lawyer",
"Merger & Acquisition Lawyers",
"Trademark Lawyers",
"Tax Lawyer",
"Pensions and Incentives",
"International Law Specialists",
"Property Law and Conveyancing",
"Couriers",
"Parcel Delivery",
"Mail Delivery",
"Leaflet Delivery",
"Advertising",
"Advertising Copywriting",
"Straplines and Slogans",
"Online Media Buying",
"Print Media Purchasing",
"Radio Airtime Purchasing",
"TV Media Buying",
"Website Copywriting",
"Articles and Report Writing",
"Brochure Copywriting",
"Case Study Copywriting",
"Marketing Copywriting",
"Script Writing Services",
"Email Copywriting",
"PPC Advert Copywriting",
"SEO Copywriting and Content",
"Blog Writing Services",
"Freelance Journalists",
"Press Release Creation",
"Data Sheets",
"User Documentation",
"White Paper Writing",
"Branding & Brand Management",
"Digital Marketing Services",
"Public Relations Agency",
"Direct Mail Marketing Production",
"Email Management",
"Email Marketing",
"Marketing Agencies",
"Search Engine Optimization (SEO) Specialists",
"Social Media Marketing",
"Mobile Marketing",
"Paid Search (PPC) Specialists",
"Telemarketing",
"Affiliate Marketing",
"Marketing Strategy Consulting",
"Market Analysis",
"Market Research Surveys",
"Business Consulting",
"Data Entry",
"Commercial Paint Spraying",
"Office Moving",
"Translation",
"Water Coolers",
"Coffee Machines",
"Interpreters",
"Office Space Rental",
"General Printing",
"Business Card Printing",
"Leaflet Printing",
"Brochure Printing",
"Postcard Printing",
"Poster Printing",
"Spot Colour Printing",
"Office Stationery",
"NCR Printing",
"Canvas Printing",
"Screen Printing",
"T-shirt and Clothes Printing",
"Branded Clothing",
"Mobile Software Development",
"General Software development",
"Web Development",
"Software testing",
"Database Development",
"Hosting & Cloud Services",
"Hardware Infrastructure",
"Network Infrastructure",
"Data Destruction",
"Document Destruction",
"Data backup",
"Database security",
"Network security",
"Overall System Security",
"Office Phone Systems",
"Internet Service Provider",
"Leased Lines",
"Video Conferencing",
"Business Mobile Services",
"Network Installation and Cabling",
"Sales Training",
"Management Training",
"Prince2 Training",
"Six Sigma Training",
"Motivational Speaking",
"Florists",
"Portrait Artistry",
"CNC Machine Services",
"Crocheting",
"Custom Gift Baskets",
"Custom Jewellery",
"Electroplating",
"Embroidery",
"Engraving",
"Fine Art Consultation",
"Illustrators",
"Music Engraving",
"Plastic Fabrication",
"Powder Coating",
"Quilting",
"Scrapbooking",
"Songwriting",
"Dressmakers",
"Artists",
"3D Modeling and CAD Services",
"Animation",
"E Commerce",
"Engineering and Technical Design",
"Presentation Design",
"Print Design",
"Technical Design",
"Brochure Design",
"Advert Design",
"Brand Design",
"Business Card Design",
"Binding",
"Clothing Alteration & Tailoring",
"Suit Hire",
"Hair Extensions",
"Hair Transplants",
"Laser Hair Removal",
"Tattoo Artists",
"Tattoo Removal",
"Mortgage Advice",
"Bankruptcy Lawyer",
"Civil Lawyer",
"Contracts Lawyer",
"Court Interpreting",
"Criminal Defense Lawyer",
"Disability Lawyer",
"Divorce Lawyers",
"Estate Lawyer",
"Family Lawyers",
"Immigration Attorneys",
"Lawyers, Solicitors & Notary Publics",
"Legal Document Preparation",
"Mediation",
"Process Serving",
"Radon Mitigation",
"Traffic Lawyer",
"Wills and Estate Planning",
"McDonald's Monopoly Players",
"World Cup Workers",
"Online Eradicator",
"Wingmen & Wingwomen",
"Auctioneers",
"Therapist",
"Investment Advisors",
"Bodyguard Services",
"Personal Chef Services",
"Wardrobe Organizers",
"Independent Financial Advisors",
"Astrology Reading",
"Counselling",
"Family Counselling",
"Genealogy",
"House Sitting",
"Identity Theft Restoration",
"Life Coaching",
"Palm Reading",
"Paranormal Investigation",
"Private Investigators",
"Psychic and New Age Services",
"Psychic Reading & Mediums",
"Psychology",
"Spiritual Counselling",
"Tarot Card Reading",
"Wardrobe Consulting",
"Relationship and Marriage Counselling",
"Child Minding",
"Baby Sitting",
"Errand Running & Concierge",
"Shoe Repair & Cobbler Services",
"Home & Domiciliary Care",
"Dry Cleaning & Laundry Services",
"Au Pair Agencies",
"Pet Care",
"Dog Training",
"Dog Walking",
"Pet Sitting",
"Pet Trainers",
"Dog & Pet Grooming",
"Farriers",
"Kennels",
"Livery Yards and Stables",
"Pet Funerals and Cremations",
"Photography",
"Aerial & Drone Photography",
"Architectural Photography",
"Boudoir Photography",
"Commercial & Corporate Photographers",
"Event & Party Photography",
"Event Videography",
"Headshot Photographers",
"Nature Photography",
"Pet Photography",
"Portrait Photographers",
"Property Photography",
"Sports Photography",
"Video Editing",
"Wedding Photography",
"Engagement Photography",
"Models",
"Photo Scanning",
"Wedding Videography",
"Passport, Visa and ID Photography",
"Photography Assistants",
"Telephone System Services",
"Car & Vehicle Mechanics",
"Network, Database and IT Support",
"Dishwasher Repair",
"Exercise Equipment Repair",
"Refrigerator Repair",
"Vacuum Cleaner Repair",
"Washing Machine Repair",
"Lawn Mower Repair",
"ATM Repair",
"Coin Operated Machine Repair",
"Computer Repair",
"Data Recovery",
"Heavy Equipment Repair Services",
"Medical Equipment Repair",
"Phone or Tablet Repair",
"Pool Table Repair Services",
"Pressure Washer Repair",
"Printer and Copier Repair",
"TV & AV Repair",
"Vehicle Window Tinting",
"Car & Vehicle Bodyshops",
"Mobile Phone Unlocking",
"Removal Companies",
"Bus & Coach Hire",
"Vehicle Hire Companies",
"Limousine Hire",
"Car Cleaning & Valet",
"Airport Transfers",
"Writing Services",
"Arabic Translation",
"Cantonese Translation",
"Chinese Translation",
"Czech Translation",
"Danish Translation",
"Dutch Translation",
"Editing",
"Farsi Translation",
"French Translation",
"German Translation",
"Greek Translation",
"Hebrew Translation",
"Hindi Translation",
"Indonesian Translation",
"Italian Translation",
"Japanese Translation",
"Korean Translation",
"Latin Translation",
"Mandarin Translation",
"Medical Transcription",
"Norwegian Translation",
"Polish Translation",
"Portuguese Translation",
"CV Writing",
"Romanian Translation",
"Russian Translation",
"Sanskrit Translation",
"Scandinavian Translation",
"Somali Translation",
"Spanish Translation",
"Swahili Translation",
"Swedish Translation",
"Tagalog Translation",
"Thai Translation",
"Transcription Services",
"Turkish Translation",
"Vietnamese Translation",
"Welsh Translation",
"Botox",
"Breast Enlargement & Reductions",
"Liposuction",
"Rhinoplasty",
"Other Cosmetic Surgery",
"Private Doctors",
"Stylists",
"Dentists",
"Acupuncture & Acupressure",
"Alternative Healing",
"Hypnotherapy",
"Nutritionists & Dietitians",
"Physical Therapy",
"Psychotherapy",
"Qigong Lessons",
"Reiki Healing",
"Massage Therapy",
"Beauty Salons",
"Chiropractor",
"Adolescent Counselling",
"Addiction Therapy",
"Bereavement Counselling",
"Cancer Counselling",
"Child Counselling",
"Cognitive Behaviour Therapy",
"Couples Counselling",
"Depression Counselling",
"Dynamic Interpersonal Therapy",
"Gambling Therapy",
"Jungian Psychoanalysis",
"Post Natal Depression",
"Private Psychiatry",
"Psychodynamic Psychotherapy",
"Aromatherapy",
"Shiatsu",
"Homeopathy",
"Complementary Therapy",
"Holistic Therapy",
"Osteopathy",
"Podiatry & Chiropodists",
"Reflexology",
"Iridology",
"Personal Trainers",
"Badminton Lessons",
"Baseball Lessons",
"Basketball Lessons",
"Climbing Lessons",
"Cycling Training",
"Fencing Lessons",
"Football Coaching",
"Golf Lessons",
"Gymnastics Classes",
"Horse Riding Lessons",
"Ice Skating Lessons",
"Kayaking Lessons",
"Martial Arts Classes",
"Paragliding Lessons",
"Pilates Classes",
"Racquetball Lessons",
"Running and Jogging Lessons",
"Sailing Lessons",
"Scuba Diving Lessons",
"Skateboarding Lessons",
"Skating Lessons",
"Skiing Lessons",
"Softball Lessons",
"Surfing Lessons",
"Swimming Lessons",
"Table Tennis Coaching",
"Tai Chi Lessons",
"Tennis Lessons",
"Triathlon Coaching",
"Volleyball Lessons",
"Wakeboarding Lessons",
"Water Aerobics Lessons",
"Waterskiing Lessons",
"Yoga Classes",
"Zumba Classes",
"Capoeira Training",
"Rowing and Crew Lessons",
"Boxing Coaches",
"Cross Fit Training",
"Tutoring",
"Maths Tutoring",
"Astronomy Tutoring",
"Biology Tutoring",
"Calculus Tutoring",
"Chemistry Tutoring",
"Economics Tutoring",
"Electrical Engineering Tutoring",
"Engineering Tutoring",
"Geography Tutoring",
"History Tutoring",
"MCAT Tutoring",
"Mechanical Engineering Tutoring",
"Philosophy Tutoring",
"Physics Tutoring",
"Poetry Lessons",
"Precalculus Tutoring",
"Psychology Tutoring",
"Reading and Writing Tutoring",
"Science Tutoring",
"Social Science Tutoring",
"Statistics Tutoring",
"TOEFL Tutoring",
"Trigonometry Tutoring",
"Veterinary Science Tutoring",
"Audio Production Lessons",
"Calligraphy Lessons",
"Creative and Performing Arts Instruction",
"Crocheting Lessons",
"Drawing Classes",
"Fabric Arts Lessons",
"Fashion and Costume Design Instruction",
"Filmmaking Lessons",
"Flower Arranging Instruction",
"Furniture Design Lessons",
"Gardening Lessons",
"Glass Art Lessons",
"Glass Blowing Lessons",
"Graphic Design Instruction",
"Jewellery Making Lessons",
"Knitting Lessons",
"Metalworking Instruction",
"Photography Classes",
"Pottery Classes",
"Printmaking Lessons",
"Quilting Lessons",
"Sculpting Lessons",
"Sewing Classes",
"Silkscreening Lessons",
"Welding Instruction",
"Woodworking Instruction",
"German Lessons",
"French Lessons",
"Spanish Lessons",
"Italian Lessons",
"Turkish Lessons",
"English Lessons",
"Russian Lessons",
"Chinese Lessons",
"Portuguese Lessons",
"Dutch Lessons",
"Accounting Training",
"Adult Basic Education Tutoring",
"Bartending Training",
"Business Finance Training",
"Computer Lessons",
"Construction Safety Training",
"Cosmetology Training",
"Flight Training",
"Leadership Development Training",
"Legal Training",
"Makeup Artistry Lessons",
"Marketing Training",
"Medical Coding Training",
"Modeling Lessons",
"Music Teacher Training",
"Negotiation Training",
"Neonatal Resuscitation Program Lessons",
"Personal Finance Instruction",
"Public Speaking Lessons",
"Real Estate Training",
"Search Engine Optimization Training",
"Sign Language Lessons",
"Social Security Advice and Consultation",
"Speech & Language Therapy",
"Study Skills Training",
"Teacher Training",
"Typing Training",
"Business & Career Coaching",
"Accordion Lessons",
"Acting Classes",
"Bagpipe Lessons",
"Ballroom Dance Classes",
"Banjo Lessons",
"Bass Guitar Lessons",
"Bassoon Lessons",
"Belly Dance Lessons",
"Cello Lessons",
"Circus Arts Lessons",
"Clarinet Lessons",
"Comedy Lessons",
"Dance Choreography Lessons",
"Dance Lessons",
"Double Bass Lessons",
"Drum Lessons",
"Fiddle Lessons",
"Flute Lessons",
"French Horn Lessons",
"Guitar Lessons",
"Harmonica Lessons",
"Harp Lessons",
"Hip Hop Dance Classes",
"Keyboard Lessons",
"Mandolin Lessons",
"Music Composition Lessons",
"Music Theory Lessons",
"Oboe Lessons",
"Piano Lessons",
"Pole Dancing Classes",
"Rap Music Lessons",
"Salsa Dance Lessons",
"Saxophone Lessons",
"Tango Dance Lessons",
"Tap Dance Lessons",
"Trombone Lessons",
"Trumpet Lessons",
"Ukulele Lessons",
"Viola Lessons",
"Archery Lessons",
"Cheerleading Lessons",
"Chess Lessons",
"CPR Training",
"First Aid Training",
"Fishing Lessons",
"Kiteboarding and Kitesurfing Lessons",
"Outdoor Skills Instruction",
"Pool and Billiards Lessons",
"Safety and First Aid Instruction",
"Self Defence Classes",
"Skydiving Instruction",
"Clown Entertainment",
"Face Painting",
"Magician",
"Bouncy Castle Hire",
"Puppet Show Entertainment",
"Balloon Twisters & Entertainers",
"Venue Hire",
"Event Entertainment",
"Animal Show Entertainment",
"Balloon Artistry",
"Belly Dancing",
"Body Painting",
"Bubble Blowing",
"Caricaturing",
"Circus Acting",
"Comedians",
"Costumed Character Entertainment",
"Dance Entertainment",
"Dove Releasing",
"Fireworks Show Entertainment",
"Free Running and Parkour Performing",
"Henna Tattooing",
"Impersonating",
"Laser Show Entertainment",
"MC and Hosts",
"Mechanical Bull Rental Services",
"Miming",
"Mobile Petting Zoo Entertainment",
"Photo Booth Hire",
"Pony Riding",
"Storytellers",
"Stunt Show Entertainment",
"Temporary Tattoo Artistry",
"Fun Fair Hire",
"Restaurant Hire",
"Catering",
"Bartending",
"Candy Buffet Services",
"Pastry Chef Services",
"Sommelier Services",
"Wedding Cakes",
"Cake Making",
"Cookery Lessons",
"Catering Van Hire",
"Acapella Group Entertainment",
"Band Entertainment",
"Big Band and Swing Band Entertainment",
"Blues Band Entertainment",
"Brass Band Entertainment",
"Christian Music Band Entertainment",
"Country Band Entertainment",
"DJ",
"Hip Hop Performers",
"Jazz Band Entertainment",
"Karaoke",
"Latin Band Entertainment",
"Mariachi Band Entertainment",
"Music Duo Entertainment",
"Party Music Consultants",
"Pop Band Entertainment",
"Quintet Entertainment",
"R and B Entertainment",
"Reggae Band Entertainment",
"Rock Band Entertainment",
"Solo Musician Entertainment",
"String Quartet Entertainment",
"Wedding Music Bands",
"Bagpipers",
"Composers",
"Event & Party Planners",
"Actor",
"AV Equipment Rental for Events",
"Commercial, Movie, or Music Videography",
"Craft Party Planning",
"Event Decorator and Designing",
"Party Rental Supplies",
"Staging and Trussing",
"Wedding Decorating",
"Wedding Planning",
"Wedding Stationery",
"Funeral Services",
"Wedding Catering",
"Wedding Dresses",
"Wedding Dress Alterations",
"Wedding Flowers",
"Wedding Venues",
"Wedding Insurance",
"Wedding Makeup",
"Wedding Hairstylist",
"Wedding Entertainment",
"Wedding DJ",
"Wedding Musicians",
"Marquee Hire",
"Engagement Videography",
"Honeymoon Planners",
"Honeymoon Travel Agencies",
"Wedding Stylist",
"Wedding Jewellery",
"Wedding Photo Booths",
"Wedding Sound & Lighting",
"Wedding Celebrants",
"Wedding Toastmasters",
"Wedding Car Hire",
"Vintage Car Hire",
"Stag & Hen Venues",
"Bridesmaids & Groomsmen",
"Satellite & Set Top Boxes",
"Home Automation Services",
"TV & Home Theatre Installation or Mounting",
"Thermostat Installation & Repair",
"TV Installation & Mounting",
"Aerial Installation",
"Aerial Repairs & Maintenance",
"Digital Home Networking",
"Electronic Blinds, Shutters & Curtains Installation",
"Electronic Blinds, Shutters & Curtains Repair",
"TV & Home Theatre Servicing",
"Architectural Services",
"General Surveyor",
"Residential Valuations Surveyor",
"Property Inspection & Inventory",
"Home Energy Auditing & Energy Performance Certificates",
"Loft Conversions",
"Thermal Imaging",
"Garage Conversions",
"Cellar & Basement Conversion",
"Planning Consultancy",
"Property Extensions",
"Quantity Surveyor",
"Boundary Surveyor",
"Commercial Building & Structural Surveyor",
"Commercial Valuations Surveyor",
"Land Surveyor",
"Party Wall Surveyor",
"Residential Building & Structural Surveyor",
"Structural Engineer",
"Plumbing Pipe Repair",
"Bathroom Installation & Remodel",
"Cabinetry",
"Pipe-fitters",
"Bathroom Tilers",
"Sealing, Grouting & Caulking",
"Shower Installation",
"Stone or Tile Flooring Installation",
"Stone or Tile Flooring Repair",
"Tile and Grout Cleaning",
"Vinyl or Linoleum Installation",
"Vinyl or Linoleum Repair",
"Bathroom & Shower Plumbing",
"Bathroom Design & Planning",
"Bathroom Repair",
"General Bricklaying",
"Barbecue Installation",
"Glass Block Installers",
"Pebble Dash Application",
"Fireplace & Chimney Installation",
"Brick & Block Paving Services",
"Brick Wall Construction",
"Dry Stone Wall Construction",
"Fireplace & Chimney Service & Repair",
"Outdoor Walls & Retaining Wall Construction",
"Repointing",
"Retaining Wall Construction",
"Asbestos Removal",
"General Builders",
"Asphalt Installation",
"Awning Installation",
"Backhoe Services",
"Concrete Delivery",
"Driveway Installation",
"Concrete Installation",
"Concrete Removal",
"Concrete Repair & Maintenance",
"Concrete Sawing",
"Deck or Porch Construction",
"Demolition Services",
"Fence & Gate Installation",
"Flat Roofing Installation",
"Foundation Services",
"Greenhouse Construction",
"Waste Management",
"Concrete Levelling",
"Porch, Patio & Canopy Installation",
"Patio Services",
"Post Construction Property Cleanup",
"Roofing Installation or Replacement",
"Roof Repair",
"Septic Tanks & Soakaway Installation",
"Septic Tanks & Soakaway Repair & Maintenance",
"Cladding Installation or Replacement",
"Damp Proofing",
"Weatherproofing",
"Window Fitters",
"Kitchen Installation & Remodelling",
"Stairs",
"Fitted Wardrobe Installation",
"Concrete Flooring Installation",
"Drywall & Plasterboard Installation",
"Building Frame Carpentry",
"Velux / Skylight Window Installation",
"Water Damage Cleanup and Restoration",
"Conservatory Installation",
"Scaffolding Hire",
"Accessibility Adaptation",
"Cladding Repair & Maintenance",
"Deck or Porch Maintenance",
"Disability & Accessibility Home Installation",
"Garage & Outbuilding Construction",
"Garage & Outbuilding Remodel",
"Garage & Outbuilding Repairs",
"Kitchen Refurbishment",
"Internal Renovation & Reconfiguration",
"Roofing Leadwork",
"Sash Window Installation",
"Sash Window Maintenance",
"Site Preparation",
"Metal Staircase Installation or Replacement",
"Wooden Staircase Installation or Replacement",
"Structural Steel Work",
"Deep Cleaning Services",
"Gutter Cleaning",
"Hot Tub and Spa Cleaning",
"Pressure Washing",
"Swimming Pool Cleaning",
"Window Cleaners",
"Commercial & Office Cleaning",
"Odour Removal",
"Carpet Cleaning",
"House Cleaning",
"Rug Cleaning",
"Steam Cleaning",
"Upholstery and Furniture Cleaning",
"Chimney Cleaning",
"Drain & Sewer Clearing",
"Driveway Cleaning",
"Oven Cleaning",
"Brick & Stone Cleaning",
"Deck or Porch Cleaning",
"Duct & Vent Cleaning",
"End of Tenancy Cleaning",
"Garden Clearance",
"Skip Hire",
"House Clearance",
"Specialist Masonry Construction Services",
"Specialist Masonry Repair and Maintenance",
"Interior Plastering & Rendering",
"Banister & Railing Installation",
"General Carpentry",
"Mural Painting",
"Fine Woodworking",
"Worktops & Splashback Installation",
"General Fitted Furniture",
"Furniture Restoration",
"Picture Framing",
"Shelving Installation",
"Bespoke Furniture Design & Build",
"Bespoke Kitchen Furniture Design & Build",
"Bespoke Wooden Doors",
"Period Restorations",
"Furniture & Upholstery Suppliers",
"Residential Interior Designers",
"Home Staging",
"Shutter, Blind & Curtain Design",
"Landscape Design",
"Signwriting",
"Kitchen Design & Planning",
"Disability & Accessibility Planning",
"Commercial Interior Designers",
"Interior Lighting Designer",
"Asphalt Repair & Maintenance",
"Awning Repair & Maintenance",
"Patio Cover Repair and Maintenance",
"Gazebo Installation",
"Gazebo Repair and Maintenance",
"Driveway Maintenance",
"Electricians",
"Holiday Lighting Installation",
"Hot Tub and Spa Installation",
"Hot Tub and Spa Repair",
"Outdoor Lighting & Power",
"Solar Panel Cleaning",
"Solar Panel Installation",
"Solar Panel Repair",
"Appliance Installation & Removal",
"Appliance Repair",
"Lamp Installation",
"Switches and Outlets",
"Rewiring",
"Ceiling Fan Installation and Repair",
"Fan Installation",
"Fan Service & Repair",
"Generator Repair",
"Interior Lighting Installation",
"Refrigerator Installation",
"Washing Machine Installation",
"Water Heater Repair or Maintenance",
"Water Softening & Purification System Installation",
"Electrical Inspections & PAT Testing",
"Under Floor Heating - Electric System Repair & Maintenance",
"Under Floor Heating Installation",
"Water Heater Installation",
"Water Softening & Purification System Maintenance",
"Geothermal Energy Services",
"Home Insulation",
"Double Glazed Windows & Door Installation",
"Draft Proofing & Window Insulation",
"Solar Heating System Installation",
"Solar Heating System Maintenance",
"Carpet Fitting & Replacement",
"Carpet Repair",
"Floor Tiling",
"Hardwood Floor Installation",
"Hardwood Floor Sanding & Finishing",
"Hardwood Floor Repair or Partial Replacement",
"Kitchen Tiling",
"Laminate Floor Installation",
"Plastic & Rubber Flooring Installation",
"Plastic & Rubber Flooring Maintenance",
"Under Floor Heating - Water System Repair & Maintenance",
"Wildlife Control",
"Gardening",
"Boulder Placement",
"Fence & Gate Repair",
"Snow Ploughing",
"Pond & Water Feature Installation",
"Pond & Water Feature Repair & Maintenance",
"Well System Work",
"Artificial Turf Installation",
"Fertilizing",
"Landscaping",
"Lawn Care",
"Play Equipment Construction",
"Play Equipment Repair",
"Lawn Turfing & Seeding",
"Garden Sprinkler System Installation",
"Garden Sprinkler System Repair & Maintenance",
"Tree and Shrub Planting, Maintenance, or Removal",
"Tree Surgery & Removal",
"Xeriscaping",
"Ironing Services",
"Arbor, Pergola, & Trellis Installation",
"Artificial Turf Repair",
"Garden Shed Construction",
"Security Fence Installation",
"Soil Irrigation & Drainage",
"Grass Cutting",
"Ironmongery & Metalwork",
"Security Gate & Barrier Installation",
"Painting & Decoration - Interior",
"Exterior Painting",
"Garage Door Installation",
"Garage Door Repairs",
"Internal Door Fitter",
"Door Repair Services",
"Handyman",
"Paint Removal & Stripping",
"General Tiling",
"Child Proofing",
"Furniture & Flat Pack Assembly",
"Picture Hanging and Art Installation",
"Taps & Fixtures Installation",
"Wallpapering",
"Drywall & Plasterboard Repair",
"Gutter Repairs & Maintenance",
"Man & Van Services",
"Taps, Fixtures & Pipes Maintenance",
"Worktops & Splashback Repair",
"General Plumbing",
"Air Conditioning Service & Repair",
"Boiler Repair or Maintenance",
"Air Conditioning Installation",
"Duct & Vent Maintenance or Repair",
"Central Heating System Installation & Replacement",
"Central Heating System Repair & Maintenance",
"Mould Inspection & Remediation",
"Mould Remediation",
"Boiler Installation or Replacement",
"Boiler Service",
"Gas Appliance Installation",
"Gas Appliance Maintenance or Repair",
"Gas Safety Check",
"Timber Preservation, Woodworm & Rot",
"Blacksmithing",
"Metal Fabrication",
"Metal Metalwork",
"Welding",
"Granite Worktop Installation",
"Fire Alarm System Installation",
"Burglar, Security & Intruder Alarm Installation",
"Locksmith",
"Fire Extinguisher Inspection",
"Automated Gates & Bollards",
"Access Control & Door Entry",
"CCTV Installation",
"External Shutter Installation",
"Fire Sprinkler System Installation",
"Security Shutter Installation",
"Security Shutter Maintenance",
"Coving, Cornice, Trim, & Moulding",
"Pest Control",
"Bed Bug Extermination",
"Commercial Pest Control",
"Soundproofing",
"Gutter Installation or Replacement",
"Aquarium Services",
"Dishwasher Installation",
"Property Management",
"Estate & Lettings Agents",
"Off-Site Storage Services",
"Relocation Consultants",
"Metal Roof Installation",
"Slate Roof Installation",
"Tile Roof Installation",
"Thatched Roof Installation",
"Thatching Maintenance",
"Roof Cleaning",
"Sawmilling",
"Seismic Retrofitting",
"Decorative Glazing & Stained Glass",
"Sports Surface Installation",
"Sports Surface Maintenance",
"Above Ground Swimming Pool Installation",
"Swimming Pool Installation",
"Swimming Pool Repair",
"Glazier",
"Storm Windows",
"Window Screen Repair",
"Window Protection & Treatments",
"Drapes and Curtains",
"Window Blinds",
"External Door Fitter",
        ];
    }

}